# ============================================================
# Lista de Control de Acceso (ACL) — Broker MQTT Hogar Conectado
# Autor: Herminio Jose Aquino Ramos
# Módulo 9: Seguridad en IoT — CEUPE
# ============================================================

# ===== PANEL PRINCIPAL =====
# Solo lee eventos de todas las estancias y publica comandos
user panel
topic read home/+/+/event
topic write home/+/+/cmd

# ===== SALON =====
# Publica eventos propios y recibe comandos de su estancia
user salon
topic write home/salon/+/event
topic read  home/salon/+/cmd

# ===== COCINA =====
user cocina
topic write home/cocina/+/event
topic read  home/cocina/+/cmd

# ===== HABITACION =====
user habitacion
topic write home/habitacion/+/event
topic read  home/habitacion/+/cmd
