# Configuración del listener TLS — Puerto 8883
# Cifra todas las comunicaciones MQTT con SSL/TLS

listener 8883
protocol mqtt

cafile   /etc/mosquitto/ca.crt
certfile /etc/mosquitto/server.crt
keyfile  /etc/mosquitto/server.key
